version: "3"

services:

  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: store
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    ports:
      - "15432:5432"

  store:
    build: store/
    restart: always
    depends_on:
      - postgres
    volumes:
      - ./store:/app/store
      - ./proto:/app/proto

  user_api:
    build: user-api/
    restart: always
    ports:
      - "3005:3005"
    depends_on:
      - store
    volumes:
      - ./user-api:/app/user-api
      - ./proto:/app/proto
